### ISSUE TITLE
Shows error when we enter email

### ISSUE THREAD

**Issue by shirshak55** [TobyColeman/Treehouse-Video-Downloader#5]
It shows error like this

-------- Login --------
email: xyz_validlogin@gmail.com
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    auth_menu()
  File "main.py", line 45, in auth_menu
    email = input("email: ")
  File "<string>", line 1
    xyz_validlogin@gmail.com
                 ^
SyntaxError: invalid syntax

**Comment by AmagiDDmxh** [comment]
I'm been check out this issues. they are have not the problem.

**Comment by bloggervista** [comment]
Hello . Can you write documentation step by step as i am getting error ?
Whenever i try to do python main.py it gives me error like that

**Comment by bloggervista** [comment]
I am using c9 ubuntu 14.04 for that

**Comment by niteshkumarniranjan** [comment]
use the email inside "".
For example "abc@gmail.com"
